export default [
    {
        id:1,
        name:'Programming',
        icon:'/coding.webp',
        prompt:'',
    },
    {
        id:2,
        name:'Development',
        icon:'/development.webp',
        prompt:'',
    },
    {
        id:3,
        name:'Interview',
        icon:'/interview.png',
        prompt:'',
    },
    {
        id:4,
        name:'Deployment',
        icon:'/deploy.png',
        prompt:'',
    },
    {
        id:5,
        name:'Others',
        icon:'/interview.png',
        prompt:'',
    },
    
]